/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package PoinOfSale;

import java.sql.PreparedStatement;
import java.awt.Frame;
import java.sql.Connection;
import java.sql.Statement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ACER
 */
public class Admin extends javax.swing.JFrame {
    UserProfile u;
    private UserProfile up;

    /**
     * Creates new form Admin
     */
    public Admin() {
        initComponents();
    }

    public Admin(UserProfile up){
        initComponents();
        
        this.u = up;
        labelFullname.setText(u.getFullname());
        
        viewData("");
        viewDataProduct("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        labelFullname = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        btn_tambah = new javax.swing.JButton();
        btn_ubah = new javax.swing.JButton();
        btn_hapus = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        logocari = new javax.swing.JLabel();
        txtkey = new javax.swing.JTextField();
        txt_refreash = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txt_tabel = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        btn_tambah_produk = new javax.swing.JButton();
        btn_ubah_produk = new javax.swing.JButton();
        btn_hapus1 = new javax.swing.JButton();
        jPanel13 = new javax.swing.JPanel();
        logocari1 = new javax.swing.JLabel();
        txtproduk = new javax.swing.JTextField();
        txt_refreash1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txt_tbl_produk = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));

        jPanel10.setBackground(new java.awt.Color(153, 204, 255));

        jLabel3.setText("Welcome");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labelFullname, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(60, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelFullname, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        btn_tambah.setText("Tambah");
        btn_tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambahActionPerformed(evt);
            }
        });

        btn_ubah.setText("Ubah");
        btn_ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubahActionPerformed(evt);
            }
        });

        btn_hapus.setText("Hapus");
        btn_hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapusActionPerformed(evt);
            }
        });

        jPanel5.setPreferredSize(new java.awt.Dimension(353, 30));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logocari.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        logocari.setText(" ");
        jPanel5.add(logocari, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 20, -1));

        txtkey.setPreferredSize(new java.awt.Dimension(64, 30));
        txtkey.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtkeyKeyReleased(evt);
            }
        });
        jPanel5.add(txtkey, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, -1));

        txt_refreash.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refreash.png"))); // NOI18N
        txt_refreash.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_refreashMouseClicked(evt);
            }
        });

        txt_tabel.setAutoCreateRowSorter(true);
        txt_tabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NO", "FULLNAME", "USERNAME", "PASSWORD", "JABATAN"
            }
        ));
        txt_tabel.getTableHeader().setReorderingAllowed(false);
        txt_tabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tabelMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(txt_tabel);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(btn_tambah)
                .addGap(12, 12, 12)
                .addComponent(btn_ubah)
                .addGap(12, 12, 12)
                .addComponent(btn_hapus)
                .addGap(12, 12, 12)
                .addComponent(txt_refreash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 152, Short.MAX_VALUE)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(jScrollPane2)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_ubah, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btn_hapus, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_refreash, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 386, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Data User", jPanel3);

        btn_tambah_produk.setText("Tambah");
        btn_tambah_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tambah_produkActionPerformed(evt);
            }
        });

        btn_ubah_produk.setText("Ubah");
        btn_ubah_produk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ubah_produkActionPerformed(evt);
            }
        });

        btn_hapus1.setText("Hapus");
        btn_hapus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hapus1ActionPerformed(evt);
            }
        });

        jPanel13.setPreferredSize(new java.awt.Dimension(353, 30));
        jPanel13.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logocari1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/search.png"))); // NOI18N
        logocari1.setText(" ");
        jPanel13.add(logocari1, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, 20, -1));

        txtproduk.setPreferredSize(new java.awt.Dimension(64, 30));
        txtproduk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtprodukKeyReleased(evt);
            }
        });
        jPanel13.add(txtproduk, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 330, 30));

        txt_refreash1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/refreash.png"))); // NOI18N
        txt_refreash1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_refreash1MouseClicked(evt);
            }
        });

        txt_tbl_produk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "NO", "ID", "KODE", "NAMA", "GAMBAR", "KATEGORI", "SUPPLIER", "HARGA JUAL", "HARGA BELI", "STOK"
            }
        ));
        txt_tbl_produk.getTableHeader().setReorderingAllowed(false);
        txt_tbl_produk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txt_tbl_produkMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(txt_tbl_produk);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btn_tambah_produk)
                .addGap(12, 12, 12)
                .addComponent(btn_ubah_produk)
                .addGap(12, 12, 12)
                .addComponent(btn_hapus1)
                .addGap(12, 12, 12)
                .addComponent(txt_refreash1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 156, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 356, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_tambah_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(btn_ubah_produk, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btn_hapus1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_refreash1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Data Produk", jPanel4);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 688, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 399, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Transaksi", jPanel6);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubahActionPerformed

        int n = txt_tabel.getSelectedRow();
        if(n > 0){
            UbahUser U = new UbahUser(this, true);
            U.setVisible(true);
            int ID = Integer.parseInt(txt_tabel.getValueAt(n, 0).toString());
            String FN = txt_tabel.getValueAt(n, 2).toString();
            String US = txt_tabel.getValueAt(n, 3).toString();
            String PS = txt_tabel.getValueAt(n, 4).toString();
            String JB = txt_tabel.getValueAt(n, 5).toString();
        
            U.setid(ID);
            U.setfn(FN);
            U.setus(US);
            U.setps(PS);
            U.setjb(JB);
        
        }else{
            JOptionPane.showMessageDialog(this, "Anda belum memilih baris data");
        }
    }//GEN-LAST:event_btn_ubahActionPerformed

    private void txtkeyKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkeyKeyReleased
        // TODO add your handling code here:
        String key = txtkey.getText();
        String w = "WHERE "
                + "fullname LIKE '%"+key+"%' "
                + "OR username LIKE '%"+key+"%' "
                + "OR password LIKE '%"+key+"%' "
                + "OR jabatan LIKE '%"+key+"%'";
        viewData(w); 
    }//GEN-LAST:event_txtkeyKeyReleased

    private void btn_tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambahActionPerformed
        // TODO add your handling code here:
        TambahUser T = new TambahUser(this, true);
        T.setVisible(true);
    }//GEN-LAST:event_btn_tambahActionPerformed

    private void txt_tabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tabelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tabelMouseClicked

    private void btn_hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapusActionPerformed
        int n = txt_tabel.getSelectedRow();
        if(n > 0){
            int id = Integer.parseInt(txt_tabel.getValueAt(n, 0).toString());
            String fullname = txt_tabel.getValueAt(n, 2).toString();
            
            int opsi = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin ingin menghapus data "+fullname+"?", 
                    "Hapus Data", 
                    JOptionPane.YES_NO_OPTION);
            if(opsi == 0){
                String Q = "DELETE FROM akun "
                        + "WHERE id="+id;
                
                try {
                    Connection K = koneksi.Go();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewData(""); 
                    JOptionPane.showMessageDialog(this, "Data "+ fullname +" telah terhapus");
                } catch (SQLException e) {
                }
            }
            
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data");
        }
    }//GEN-LAST:event_btn_hapusActionPerformed

    private void txt_refreashMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_refreashMouseClicked
        txtkey.setText(""); 
        viewData(""); 
    }//GEN-LAST:event_txt_refreashMouseClicked

    private void btn_tambah_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tambah_produkActionPerformed

    }//GEN-LAST:event_btn_tambah_produkActionPerformed

    private void btn_ubah_produkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ubah_produkActionPerformed
        int n = txt_tbl_produk.getSelectedRow();
        if (n > 0){
            UbahProduk U = new UbahProduk(this, true);
            U.setVisible(true);
            int ip = Integer.parseInt(txt_tbl_produk.getValueAt(n, 0).toString()) ;
            String kp = txt_tbl_produk.getValueAt(n, 2).toString();
            String np = txt_tbl_produk.getValueAt(n, 3).toString();
            String gp = txt_tbl_produk.getValueAt(n, 4).toString();
            int kgp = Integer.parseInt(txt_tbl_produk.getValueAt(n, 5).toString());
            int slp = Integer.parseInt(txt_tbl_produk.getValueAt(n, 6).toString());
            double hj = Double.parseDouble(txt_tbl_produk.getValueAt(n, 7).toString());
            double hb = Double.parseDouble(txt_tbl_produk.getValueAt(n, 8).toString());
            int sp = Integer.parseInt(txt_tbl_produk.getValueAt(n, 9).toString());
            
            U.setip(ip);
            U.setkp(kp);
            U.setnp(np);
            U.setgp(gp);
            U.setkgp(kgp);
            U.setslp(slp);
            U.sethj(hj);
            U.sethb(hb);
            U.setsp(sp);
            
        }
    }//GEN-LAST:event_btn_ubah_produkActionPerformed

    private void btn_hapus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hapus1ActionPerformed
        // TODO add your handling code here:
        int n = txt_tbl_produk.getSelectedRow();
        if(n != -1){
            int id = Integer.parseInt(txt_tbl_produk.getValueAt(n, 0).toString());
            
            int pilihan = JOptionPane.showConfirmDialog(this, 
                    "Apakah Anda yakin untuk menghapus data produk ini?",
                    "Hapus Data",JOptionPane.YES_NO_OPTION);
            if(pilihan == 0){
                //yes
                String Q = "DELETE FROM akun WHERE id="+id+" ";
                try {
                    Connection K = koneksi.Go();
                    Statement S = K.createStatement();
                    S.executeUpdate(Q);
                    viewData(""); 
                } catch (SQLException e) {
                }
            }else {
                //no
            }  
        }else {
            JOptionPane.showMessageDialog(this, "Anda belum memilih data"); 
        
        }
    }//GEN-LAST:event_btn_hapus1ActionPerformed

    private void txtprodukKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtprodukKeyReleased
        // TODO add your handling code here:
        String key = txtproduk.getText();
        String w = "WHERE "
                + "nama_produk LIKE '%"+key+"%' "
                + "OR kategori_produk LIKE '%"+key+"%' "
                + "OR supplier_produk LIKE '%"+key+"%' "
                + "OR harga_jual LIKE '%"+key+"%'";
        
        viewDataProduct(w); 
    }//GEN-LAST:event_txtprodukKeyReleased

    private void txt_refreash1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_refreash1MouseClicked
        // TODO add your handling code here:
        txtkey.setText(""); 
        viewDataProduct(""); 
    }//GEN-LAST:event_txt_refreash1MouseClicked

    private void txt_tbl_produkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txt_tbl_produkMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_tbl_produkMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_hapus;
    private javax.swing.JButton btn_hapus1;
    private javax.swing.JButton btn_tambah;
    private javax.swing.JButton btn_tambah_produk;
    private javax.swing.JButton btn_ubah;
    private javax.swing.JButton btn_ubah_produk;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel labelFullname;
    private javax.swing.JLabel logocari;
    private javax.swing.JLabel logocari1;
    private javax.swing.JLabel txt_refreash;
    private javax.swing.JLabel txt_refreash1;
    public static javax.swing.JTable txt_tabel;
    public static javax.swing.JTable txt_tbl_produk;
    private javax.swing.JTextField txtkey;
    private javax.swing.JTextField txtproduk;
    // End of variables declaration//GEN-END:variables

    public static void viewData(String where) {
        try {
            DefaultTableModel m = (DefaultTableModel) txt_tabel.getModel();
            m.getDataVector().removeAllElements();
            Connection K = koneksi.Go();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM akun "+where;
            ResultSet R = S.executeQuery(Q);
            int n = 1;
            while (R.next()) {                 
                int id_akun = R.getInt("id");
                String fullname = R.getString("fullname");
                String username = R.getString("username");
                String password = R.getString("password");
                String jabatan = R.getString("jabatan");
                Object[] data = {id_akun, n, fullname, username, password, jabatan};
                m.addRow(data); 
                n++;
            }
            
            txt_tabel.getColumnModel().getColumn(0).setMinWidth(0);
            txt_tabel.getColumnModel().getColumn(0).setMaxWidth(0);
            
        } catch (SQLException e) {
            //error handling
        }
    }
    
        public static void viewDataProduct(String where) {
        try {
            DefaultTableModel m = (DefaultTableModel) txt_tbl_produk.getModel();
            //m.getDataVector().removeAllElements();
            for (int i = m.getRowCount()-1; i >=0; i--) {
                m.removeRow(i); 
            }
            
            Connection K = koneksi.Go();
            Statement S = K.createStatement();
            String Q = "SELECT * FROM produk "+where;
            ResultSet R = S.executeQuery(Q);
            int n = 1;
            while (R.next()) {                 
                int id_produk = R.getInt("id_produk"); 	 	 	 	 	 	
                String kode_produk = R.getString("kode_produk");
                String nama_produk = R.getString("nama_produk");
                String gambar_produk = R.getString("gambar_produk");                
                int kategori_produk = R.getInt("kategori_produk");
                int supplier_produk = R.getInt("supplier_produk");
                double harga_jual = R.getDouble("harga_jual");
                double harga_beli = R.getDouble("harga_beli");
                int stok_produk = R.getInt("stok_produk");
                Object[] data = {n, id_produk,kode_produk, nama_produk, gambar_produk,
                kategori_produk, supplier_produk, harga_beli, harga_jual, stok_produk};
                m.addRow(data); 
                n++;
            }
            
            txt_tbl_produk.getColumnModel().getColumn(0).setMinWidth(0);
            txt_tbl_produk.getColumnModel().getColumn(0).setMaxWidth(0);
            
        } catch (SQLException e) {
            //error handling
        }
    }

}
